PlagueHO/LabBuilder

- LabBuilder/LabBuilder.psm1
- LabBuilder/Samples/Sample_WS2012R2_DCandDHCPOnly.xml
- LabBuilder/Samples/Sample_WS2012R2_DomainClustering.xml
- LabBuilder/Samples/Sample_WS2012R2_DomainComplete.xml
- LabBuilder/Samples/Sample_WS2012R2_Simple.xml
- LabBuilder/Samples/Sample_WS2016TP4_DCandDHCPOnly.xml
- LabBuilder/Tests/PesterTestConfig/PesterTestConfig.OK.xml
- LabBuilder/Tests/PesterTestConfig/expectedcontent/ExpectedSwitches.json
- LabBuilder/Tests/PesterTestConfig/expectedcontent/ExpectedVMs.json
- LabBuilder/Tests/Unit/LabBuilder.tests.ps1
- LabBuilder/Tests/Unit/lib/switch.tests.ps1
- LabBuilder/lib/dsc.ps1
- LabBuilder/lib/switch.ps1
- LabBuilder/lib/vm.ps1
- README.md
Adding a LabId setting to a configuration will cause Switch names, Adapter names and VM names to be prepended with the LabId.
> Add Settings\LabId support - Fixes #64

- LabBuilder/LabBuilder.psm1
Fixes an issue where you will get an error if (Get-NetAdapter | Select-Object -First 1) returns another Hyper-V adapter instead of a physical netadapter.
> External switch no longer sets another Hyper-V Adapter as it's NetAdapterName

- LabBuilder/DSCLibrary/DC_FORESTPRIMARY.DSC.ps1
- LabBuilder/Samples/Sample_WS2012R2_DCandDHCPOnly.xml
- LabBuilder/Samples/Sample_WS2012R2_DomainClustering.xml
- LabBuilder/dsclibrary/DC_FORESTDOMAIN.DSC.ps1
- LabBuilder/samples/Sample_WS2012R2_MultiForest.xml
- README.md
* dsclibrary\DC_FORESTDOMAIN.DSC: New DSC Library config for creating child domains in an existing forest.
* Samples\Sample_WS2012R2_MultiForest.xml: Added child domains.
> Add DSC Domain in Existing Forest - Fixes #142

- LabBuilder/docs/changelist.md
- LabBuilder/lib/dsc.ps1
- LabBuilder/lib/vhd.ps1
- appveyor.yml
* GetDSCNetworkingConfig: Fix DSC error occuring when a blank DNS Server address or Default Gateway address is set on an Adapter.
* InitializeVhd: Prevent unnecessary results of disk partitioning and volume creation to console.
Also fixes #152
>  Fix DSC error occuring when a blank DNS Server specified - Fixes #153

- LabBuilder/LabBuilder.psm1
- LabBuilder/docs/changelist.md
* Start-Lab: Improved readability if timeout detect code.
* Stop-Lab: Improved readability if timeout detect code.
Ensure all VMs are stopped in a Bootphase, even if timeout occurs.
> Ensure all VMs are stopped in a Bootphase, even if timeout occurs - Fixes #162

- LabBuilder/docs/changelist.md
- LabBuilder/lib/dsc.ps1
* StartDSCDebug.ps1: Added a WaitForDebugger parameter to StartDSCDebug.ps1 that will cause LCM to start with debugging mode enabled.
> Added a WaitForDebugger parameter to StartDSCDebug - Fixes #163

- LabBuilder/LabBuilder.psm1
- LabBuilder/docs/changelist.md
- LabBuilder/docs/labbuilderconfig-schema.md
- LabBuilder/en-us/LabBuilder_LocalizedData.psd1
- LabBuilder/lib/utils.ps1
- LabBuilder/schema/labbuilderconfig-schema.xsd
- LabBuilder/support/Convert-WindowsImage.ps1
- LabBuilder/tests/pestertestconfig/PesterTestConfig.OK.xml
- LabBuilder/tests/unit/LabBuilder.tests.ps1
- README.md
This PR contains the following fixes/changes:
* Support\Convert-WindowsImage.ps1: Updated to March 2016 version so that DISM path can be specified.
* labbuilder-schema.xsd: Added Settings\DismPath attribute so that path to DISM can be specified.
* Failure to validate Lab configuration XML will terminate any cmdlet immediately.
* Any failure in Install-Lab will cause immediate build termination.
- Fixes #179 
@m0rgenthau:
What I've done is added a new **dismpath** attribute to the <Settings> in the config that allows you to specify an alternate path to the location where DISM is (in your case C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\amd64\DISM).
If set, this dismpath will be passed to Convert-WindowsImage (they added a new option to all the path …
> Improve Handling of Convert-WindowsImage errors and support alternate DISM location - fixes #179

- LabBuilder/docs/changelist.md
- LabBuilder/lib/vm.ps1
Fixes PlagueHO/LabBuilder/#183
Name of integrationservice is now detected by ID.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/184)
> Fixed culture related name of IntegrationService Heartbeat

- LabBuilder/LabBuilder.psm1
- LabBuilder/docs/changelist.md
- LabBuilder/docs/labbuilderconfig-schema.md
- LabBuilder/en-us/LabBuilder_LocalizedData.psd1
- LabBuilder/lib/vhd.ps1
- LabBuilder/schema/labbuilderconfig-schema.xsd
- LabBuilder/tests/pestertestconfig/vhdfiles/Windows Server 2016 TP4 Datacenter Core.vhdx
- LabBuilder/tests/pestertestconfig/vhdfiles/Windows Server 2016 TP4 Datacenter Full.vhdx
- LabBuilder/tests/unit/LabBuilder.tests.ps1
- LabBuilder/tests/unit/lib/vhd.tests.ps1
* Generalized Nano Server package support.
* Both ResourceMSU and Nano Server packages can now be installed on Template VHDs and Virtual Machines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/186)
> Generalized Nano Server package support - Fixes #177

- LabBuilder/docs/changelist.md
- LabBuilder/lib/vhd.ps1
- LabBuilder/tests/unit/lib/vhd.tests.ps1
* Automatically add Microsoft-NanoServer-DSC-Package.cab to new Nano Server VMs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/188)
> Automatically add Microsoft-NanoServer-DSC-Package.cab to new Nano Server VMs - Fixes #187

- LabBuilder/LabBuilder.psm1
- LabBuilder/docs/changelist.md
- LabBuilder/docs/labbuilderconfig-schema.md
- LabBuilder/en-us/LabBuilder_LocalizedData.psd1
- LabBuilder/schema/labbuilderconfig-schema.xsd
- LabBuilder/tests/pestertestconfig/PesterTestConfig.OK.xml
- LabBuilder/tests/pestertestconfig/expectedcontent/ExpectedSwitches.json
- LabBuilder/tests/unit/LabBuilder.tests.ps1
* Added BindingAdapterName and BindingAdapterMac attribute to switch element to allow control over bound adapter.
The BindingAdapterName and BindingAdapterMac attributes should not be used on the same switch - either specify the name of the adapter or the MAC address. If both are specified only the MAC address is used.
If the Binding Adapter is found but is used by another external switch then an exception is thrown reporting this.
If no Binding Adapter attributes are specified then the first Physical adapter with an 'Up' status will be used. If it is already used the an exception will be thrown reporting this.
@m0rgenthau - if you get a chance, could you see if this change solves things for you? I've updated the Schema documentation with details of the new Attributes:
BindingAdapterName …
> Improve handling of External Virtual Switch adapter binding - Fixes #189

- LabBuilder/LabBuilder.psm1
- LabBuilder/docs/changelist.md
- LabBuilder/en-us/LabBuilder_LocalizedData.psd1
- LabBuilder/tests/unit/LabBuilder.tests.ps1
- LabBuilder/tests/unit/lib/dsc.tests.ps1
- LabBuilder/tests/unit/lib/switch.tests.ps1
- LabBuilder/tests/unit/lib/utils.tests.ps1
- LabBuilder/tests/unit/lib/vhd.tests.ps1
- LabBuilder/tests/unit/lib/vm.tests.ps1
* Added $Script:CurrentBuild variable to allow easier access to OS build version.
* Fix to prevent ExposeVirtualizationExtensions from being applied on Lab Hosts that don't support it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/200)
> Fix to Prevent ExposeVirtualizationExtensions from being used prior to Host 10585 - Fixes #199

- LabBuilder/LabBuilder.psm1
- LabBuilder/docs/changelist.md
- LabBuilder/en-us/LabBuilder_LocalizedData.psd1
- LabBuilder/lib/private/vhd.ps1
- LabBuilder/lib/public/templatevhd.ps1
- LabBuilder/template/labbuilderconfig-template.xml
- LabBuilder/tests/pestertestconfig/PesterTestConfig.OK.xml
- LabBuilder/tests/pestertestconfig/expectedcontent/ExpectedTemplateVHDs.json
- README.md
Nano Server package filename format for the language files changed in TP5. This is a breaking change and will cause Nano Server in TP4 to no longer be supported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/213)
> Fix to correct Nano Server language package filename

- LabBuilder/LabBuilder.psm1
- LabBuilder/docs/changelist.md
- LabBuilder/docs/labbuilderconfig-schema.md
- LabBuilder/en-us/LabBuilder_LocalizedData.psd1
- LabBuilder/lib/private/switch.ps1
- LabBuilder/lib/public/switch.ps1
- LabBuilder/samples/Sample_WS2012R2_DCandDHCPOnly_NAT.xml
- LabBuilder/schema/labbuilderconfig-schema.xsd
- LabBuilder/tests/pestertestconfig/PesterTestConfig.OK.xml
- LabBuilder/tests/pestertestconfig/expectedcontent/ExpectedSwitches.json
- LabBuilder/tests/unit/lib/private/switch.tests.ps1
- LabBuilder/tests/unit/lib/public/switch.tests.ps1
* Fixed support for NAT switches and added Switch attributes NatSubnet and NatGatewayAddress.
* Private function UpdateSwitchManagementAdapter added.
* Samples\Sample_WS2012R2_DCandDHCPOnly_NAT.xml: Added sample for testing NAT based Lab switches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/229)
> Fix Support for NAT Switches in Windows build 14295 and above - Fixes #228

- LabBuilder/docs/changelist.md
- LabBuilder/docs/labbuilderconfig-schema.md
- LabBuilder/en-us/LabBuilder_LocalizedData.psd1
- LabBuilder/lib/public/lab.ps1
- LabBuilder/samples/Sample_WS2012R2_DCandDHCPOnly_NAT.xml
- LabBuilder/samples/Sample_WS2012R2_DomainClustering.xml
- LabBuilder/schema/labbuilderconfig-schema.xsd
- LabBuilder/tests/pestertestconfig/PesterTestConfig.OK.xml
- LabBuilder/tests/unit/lib/public/lab.tests.ps1
* Added LabBuilderConfig\Settings attribute requiredwindowsbuild.
* Get-Lab: Added support for preventing a Lab from being used on a host not at the requiredwindowsbuild build version. 
* Samples\Sample_WS2012R2_DomainClustering.xml: Required build version set to 10586.
* Samples\Sample_WS2012R2_DCandDHCPOnly_NAT.xml: Required build version set to 14295.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/237)
> Added RequiredWindowsBuild setting support - Fixes #233

- LabBuilder/docs/changelist.md
- LabBuilder/dsclibrary/DC_FORESTCHILDDOMAIN.DSC.ps1
- LabBuilder/dsclibrary/DC_FORESTPRIMARY.DSC.ps1
- LabBuilder/dsclibrary/DC_SECONDARY.DSC.ps1
- LabBuilder/dsclibrary/MEMBER_DHCP.DSC.ps1
- LabBuilder/dsclibrary/MEMBER_DHCPDNS.DSC.ps1
- LabBuilder/dsclibrary/MEMBER_DHCPNPAS.DSC.ps1
- LabBuilder/dsclibrary/MEMBER_DNS.DSC.ps1
- LabBuilder/dsclibrary/MEMBER_ROOTCA.DSC.ps1
- LabBuilder/dsclibrary/MEMBER_SUBCA.DSC.ps1
- LabBuilder/dsclibrary/RODC_SECONDARY.DSC.ps1
* Added InstallRSATTools parameter DSC configurations to enable installation of applicable RSAT Management tools:
- DC_FORESTCHILDDOMAIN.DSC.ps1
- DC_FORESTPRIMARY.DSC.ps1
- DC_SECONDARY.DSC.ps1
- RODC_SECONDARY.DSC.ps1
- MEMBER_DNS.DSC.ps1
- MEMBER_DHCPNPAS.DSC.ps1
- MEMBER_DHCPDNS.DSC.ps1
- MEMBER_DHCP.DSC.ps1
- MEMBER_ROOTCA.DSC.ps1
- MEMBER_SUBCA.ps1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/241)
> *Added InstallRSATTools parameter DSC configurations - Fixes #239

- LabBuilder/docs/changelist.md
- LabBuilder/lib/public/vm.ps1
@MS-MatthewWalker - I haven't been able to test this completely yet because I'm not at home tonight so don't have access to my 14352 build machine. I'll try this tomorrow and if it works I'll merge the change to master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/252)
> Fix ExposeVirtualizationExtensions when on Windows 10 build 14352 and above - Fixes #251

- LabBuilder/docs/changelist.md
- LabBuilder/lib/public/switch.ps1
- LabBuilder/lib/public/vmtemplate.ps1
- LabBuilder/tests/unit/LabBuilder.tests.ps1
- LabBuilder/tests/unit/lib/private/dsc.tests.ps1
- LabBuilder/tests/unit/lib/private/switch.tests.ps1
- LabBuilder/tests/unit/lib/private/utils.tests.ps1
- LabBuilder/tests/unit/lib/private/vhd.tests.ps1
- LabBuilder/tests/unit/lib/private/vm.tests.ps1
- LabBuilder/tests/unit/lib/public/lab.tests.ps1
- LabBuilder/tests/unit/lib/public/resource.tests.ps1
- LabBuilder/tests/unit/lib/public/switch.tests.ps1
- LabBuilder/tests/unit/lib/public/templatevhd.tests.ps1
- LabBuilder/tests/unit/lib/public/vm.tests.ps1
- LabBuilder/tests/unit/lib/public/vmtemplate.tests.ps1
- appveyor.yml
* Fix bug using a NIC team as network adapter bound to an external switch.
* Change AppVeyor script to improve and automate deployment process.
* Mock functions added to unit tests so that can run on machines without Hyper-V installed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/266)
> Support NIC Team as External Switch Network Adapter - Fixes #265

- .markdownlint.json
- CHANGELOG.md
- src/dsclibrary/DC_FORESTCHILDDOMAIN.DSC.ps1
- src/dsclibrary/DC_FORESTPRIMARY.DSC.ps1
- src/dsclibrary/DC_SECONDARY.DSC.ps1
- src/dsclibrary/MEMBER_DHCP.DSC.ps1
- src/dsclibrary/MEMBER_DHCPDNS.DSC.ps1
- src/dsclibrary/MEMBER_DHCPNPAS.DSC.ps1
- src/dsclibrary/MEMBER_DHCPNPAS2016.DSC.ps1
- src/dsclibrary/MEMBER_DNS.DSC.ps1
- src/dsclibrary/MEMBER_FAILOVERCLUSTER_DHCP.DSC.ps1
- src/dsclibrary/MEMBER_NPS_DFSTEST.DSC.ps1
- src/dsclibrary/MEMBER_ROOTCA.DSC.ps1
- src/dsclibrary/MEMBER_SUBCA.DSC.ps1
- src/dsclibrary/MEMBER_WEBSERVER.DSC.ps1
- src/dsclibrary/STANDALONE_DHCPDNS.DSC.ps1
- src/dsclibrary/STANDALONE_INTERNET.DSC.ps1
- src/dsclibrary/STANDALONE_ROOTCA.DSC.ps1
- src/dsclibrary/STANDALONE_ROOTCA_NOSUBCA.DSC.ps1
- src/dsclibrary/modules/MyDSCResources/xCertAuthorityServer/xCertAuthorityServer.DSC.Schema.psm1
- src/dsclibrary/modules/MyDSCResources/xDHCPServer/xDHCPServer.DSC.Schema.psm1
- src/lib/private/Copy-LabOdjFile.ps1
- src/lib/private/Set-LabDSC.ps1
- `dsclibrary\MEMBER_SUBCA.DSC.ps1`:
- CAServer parameter removed from ADCSWebEnrollment - fixes [Issue-320](https://github.com/PlagueHO/LabBuilder/issues/320).
- Fix error occuring when `c:\windows\setup\scripts\` folder does not exist when
setting the advanced CA configuration settings - fixes [Issue-325](https://github.com/PlagueHO/LabBuilder/issues/325).
- `dsclibrary\MEMBER_ROOTCA.DSC.ps1`:
- CAServer parameter removed from ADCSWebEnrollment - fixes [Issue-320](https://github.com/PlagueHO/LabBuilder/issues/320).
- Change `DiscreteSignatureAlgorithm` to `AlternateSignatureAlgorithm` and set
it to 0 - fixes [Issue-322](https://github.com/PlagueHO/LabBuilder/issues/322).
- Fix error occuring when `c:\windows\setup\scripts\` folder does not exist when
setting the advanced CA …
> General Improvements & Fixes to DSC Configurations

- CHANGELOG.md
- azure-pipelines.yml
- build.yaml
- Changed Build.yml to support `ModuleBuilder` version to `1.7.0` by changing
`CopyDirectories` to `CopyPaths`.
- Changed `azure-pipelines.yml` to run on all builds and PRs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/363)
> Fix build after ModuleBuilder Update

- .vscode/settings.json
- CHANGELOG.md
- README.md
- azure-pipelines.yml
This PR removes the use of deprecated Azure DevOps agents and makes clear what versions of Windows the module is tested with.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/385)
> Removed use of deprecated Azure DevOps agents - Fixes #384
