PlagueHO/LabBuilder

- LabBuilder/LabBuilder.psm1
- LabBuilder/Samples/Sample_WS2012R2_DCandDHCPOnly.xml
- LabBuilder/Samples/Sample_WS2012R2_DomainClustering.xml
- LabBuilder/Samples/Sample_WS2012R2_DomainComplete.xml
- LabBuilder/Samples/Sample_WS2012R2_Simple.xml
- LabBuilder/Samples/Sample_WS2016TP4_DCandDHCPOnly.xml
- LabBuilder/Tests/Test_Sample_WS2012R2_DCandDHCPOnly.ps1
- LabBuilder/Tests/Test_Sample_WS2012R2_DomainClustering.ps1
- LabBuilder/Tests/Test_Sample_WS2012R2_DomainComplete.ps1
- LabBuilder/Tests/Test_Sample_WS2012R2_Simple.ps1
- LabBuilder/Tests/Test_Sample_WS2016TP4_DCandDHCPOnly.ps1
- LabBuilder/Tests/Unit/LabBuilder.tests.ps1
- LabBuilder/en-us/LabBuilder_LocalizedData.psd1
Fix to DSC.
Generalized Download code.
Removed Cert Download code.
Added new samples.
Removed WMF5 download package code.
> Remove Certificate download code - Fixes #53

- LabBuilder/LabBuilder.psm1
- LabBuilder/Samples/Sample_WS2012R2_DCandDHCPOnly.xml
- LabBuilder/Samples/Sample_WS2012R2_DomainClustering.xml
- LabBuilder/Samples/Sample_WS2012R2_DomainComplete.xml
- LabBuilder/Samples/Sample_WS2012R2_Simple.xml
- LabBuilder/Samples/Sample_WS2016TP4_DCandDHCPOnly.xml
- LabBuilder/Tests/PesterTestConfig/PesterTestConfig.OK.xml
- LabBuilder/Tests/PesterTestConfig/PesterTestConfig.SwitchFail.AdaptersSet.xml
- LabBuilder/Tests/PesterTestConfig/PesterTestConfig.SwitchFail.BadType.xml
- LabBuilder/Tests/PesterTestConfig/PesterTestConfig.SwitchFail.NoName.xml
- LabBuilder/Tests/PesterTestConfig/PesterTestConfig.SwitchFail.NoType.xml
- LabBuilder/Tests/Unit/LabBuilder.tests.ps1
- README.md
This was to make it clear that all the files for a single lab would usually be contained in this folder location - not just VM files.
> VMPath setting name changed to LabPath - Fixes #52

- LabBuilder/LabBuilder.psm1
- LabBuilder/Tests/Unit/LabBuilder.tests.ps1
- LabBuilder/en-us/LabBuilder_LocalizedData.psd1
- README.md
> Download-ResourceModule updated to use DownloadandUnzipFile function - Fixes #59

- LabBuilder/LabBuilder.psm1
- LabBuilder/Tests/PesterTestConfig/PesterTestConfig.OK.xml
- LabBuilder/Tests/Unit/LabBuilder.tests.ps1
- README.md
> Remove Hyper-V MAC Address range settings from Configuration - Fixes #75

- LabBuilder/LabBuilder.psm1
- LabBuilder/Tests/PesterTestConfig/expectedcontent/ExpectedVMs.json
- README.md
Added new VM parameters containing paths
> Fix to Wait-LabVMInit - Fixes #78

- LabBuilder/LabBuilder.psm1
- LabBuilder/Tests/Unit/lib/vm.tests.ps1
- LabBuilder/lib/vhd.ps1
- LabBuilder/lib/vm.ps1
- README.md
- appveyor.yml
This relates to Issue #86.
However, there are bugs in the CertOC.exe that is called on the guest to import the certificate so this issue is on hold for now.
> Code complete for Creating PFX certificates on Host and Uploading to Guest for Nano

- LabBuilder/LabBuilder.psd1
- LabBuilder/LabBuilder.psm1
- LabBuilder/Tests/Unit/LabBuilder.tests.ps1
- LabBuilder/Tests/Unit/lib/utils.tests.ps1
- LabBuilder/en-us/LabBuilder_LocalizedData.psd1
- LabBuilder/lib/utils.ps1
- README.md
- appveyor.yml
* VHDParentPath setting made optional. Defaults to "Virtual Machine Hard Disks" under config.
* Initialize-LabConfiguration function will create labpath and vhdparentpath folders if not exist.
* Removed Test-LabConfiguration function and tests moved to Get-LabConfiguration.
> Automatically create lab folders - Fixes #80

- LabBuilder/LabBuilder.psm1
- LabBuilder/Tests/Unit/LabBuilder.tests.ps1
- LabBuilder/en-us/LabBuilder_LocalizedData.psd1
- LabBuilder/lib/dsc.ps1
- LabBuilder/lib/vm.ps1
- README.md
* Added Disconnect-LabVM function to disconnect from a connect Lab VM.
* Fixed bug setting TrustedHosts when connecting to Lab VM.
* Added code to revert TrustedHosts when disconnecting from Lab VM.
> Fix to TrustedHosts handling - Fixes #87

- LabBuilder/LabBuilder.psd1
- LabBuilder/LabBuilder.psm1
- LabBuilder/Tests/Test_Sample_WS2012R2_DCandDHCPOnly.ps1
- LabBuilder/Tests/Test_Sample_WS2012R2_DomainClustering.ps1
- LabBuilder/Tests/Test_Sample_WS2012R2_DomainComplete.ps1
- LabBuilder/Tests/Test_Sample_WS2012R2_Simple.ps1
- LabBuilder/Tests/Test_Sample_WS2016TP4_DCandDHCPOnly.ps1
- LabBuilder/Tests/Unit/LabBuilder.tests.ps1
- LabBuilder/Tests/Unit/lib/dsc.tests.ps1
- LabBuilder/Tests/Unit/lib/utils.tests.ps1
- LabBuilder/Tests/Unit/lib/vhd.tests.ps1
- LabBuilder/Tests/Unit/lib/vm.tests.ps1
- LabBuilder/en-us/LabBuilder_LocalizedData.psd1
- LabBuilder/lib/dsc.ps1
- LabBuilder/lib/switch.ps1
- LabBuilder/lib/utils.ps1
- LabBuilder/lib/vhd.ps1
- LabBuilder/lib/vm.ps1
- README.md
> Convert Config Parameter to Lab Parameter - Fixes #117

- LabBuilder/LabBuilder.psd1
- LabBuilder/LabBuilder.psm1
- LabBuilder/Tests/Test_Sample_WS2012R2_DCandDHCPOnly.ps1
- LabBuilder/Tests/Test_Sample_WS2012R2_DomainClustering.ps1
- LabBuilder/Tests/Test_Sample_WS2012R2_DomainComplete.ps1
- LabBuilder/Tests/Test_Sample_WS2012R2_Simple.ps1
- LabBuilder/Tests/Test_Sample_WS2016TP4_DCandDHCPOnly.ps1
- LabBuilder/Tests/Unit/LabBuilder.tests.ps1
- README.md
Also completed Help on all exported functions.
Renamed Start-LabVM to Install-LabVM.
> Added Name parameter to *-Lab* functions  -Fixes #45

- LabBuilder/DSCLibrary/MEMBER_DEFAULT.ps1
- LabBuilder/DSCLibrary/MEMBER_DHCP.DSC.ps1
- LabBuilder/DSCLibrary/MEMBER_DHCPDNS.DSC.ps1
- LabBuilder/DSCLibrary/MEMBER_DHCPNPAS.DSC.ps1
- LabBuilder/DSCLibrary/MEMBER_FAILOVERCLUSTER_FS.DSC.ps1
- LabBuilder/DSCLibrary/MEMBER_FAILOVERCLUSTER_HV.DSC.ps1
- LabBuilder/DSCLibrary/MEMBER_FILESERVER.DSC.ps1
- LabBuilder/DSCLibrary/MEMBER_FILESERVER_FSRMTEST.DSC.ps1
- LabBuilder/DSCLibrary/MEMBER_FILESERVER_ISCSI.DSC.ps1
- LabBuilder/DSCLibrary/MEMBER_NLB.DSC.ps1
- LabBuilder/DSCLibrary/MEMBER_NPS.DSC.ps1
- LabBuilder/DSCLibrary/MEMBER_NPS_DFSTEST.DSC.ps1
- LabBuilder/DSCLibrary/MEMBER_REMOTEACCESS.DSC.ps1
- LabBuilder/DSCLibrary/MEMBER_ROOTCA.DSC.ps1
- LabBuilder/DSCLibrary/MEMBER_SUBCA.DSC.ps1
- LabBuilder/DSCLibrary/MEMBER_WDS.DSC.ps1
- LabBuilder/DSCLibrary/MEMBER_WSUS.DSC.ps1
- LabBuilder/DSCLibrary/RODC_SECONDARY.DSC.ps1
- LabBuilder/Samples/Sample_WS2012R2_DCandDHCPOnly.xml
- LabBuilder/Samples/Sample_WS2012R2_DomainClustering.xml
- LabBuilder/Samples/Sample_WS2012R2_DomainComplete.xml
- LabBuilder/Samples/Sample_WS2016TP4_DCandDHCPOnly.xml
to use more efficient Domain Join Method
> Updating DSC resources and Samples 

- LabBuilder/LabBuilder.psm1
- LabBuilder/Tests/PesterTestConfig/expectedcontent/ExpectedTemplateVHDs.json
- LabBuilder/en-us/LabBuilder_LocalizedData.psd1
- README.md
More work done on this change:
* Get-LabVMTemplateVHD: Converted to output array of LabVMTemplateVHD objects.
* Initialize-LabVMTemplateVHD: Converted to use LabVMTemplateVHD objects.
Check added to ensure Drive Letter is assigned to mounted ISO.
* Remove-LabVMTemplateVHD: Converted to use LabVMTemplateVHD objects.
* Readme.md: Windows Management Framework 5.0 (WMF 5.0) section added.
> Issue 119 covert get functions to custom classes

- LabBuilder/docs/changelist.md
- LabBuilder/lib/vm.ps1
* UpdateVMDataDisks: Fix to incorrectly reported Data VHD type change error.
> Fix to incorrectly reported Data VHD type change error.

- LabBuilder/LabBuilder.psd1
- LabBuilder/LabBuilder.psm1
- LabBuilder/docs/changelist.md
- LabBuilder/docs/labbuilderconfig-schema.md
- LabBuilder/en-us/LabBuilder_LocalizedData.psd1
- LabBuilder/lib/vm.ps1
- LabBuilder/schema/labbuilderconfig-schema.xsd
- LabBuilder/tests/pestertestconfig/PesterTestConfig.OK.xml
- LabBuilder/tests/pestertestconfig/expectedcontent/ExpectedResourceISOs.json
- LabBuilder/tests/pestertestconfig/expectedcontent/ExpectedVMs.json
- LabBuilder/tests/pestertestconfig/isofiles/SQL2014_FULL_ENU.iso
- LabBuilder/tests/unit/LabBuilder.tests.ps1
- LabBuilder/tests/unit/lib/vm.tests.ps1
* Added support for ISO resources to be specified in the Lab configuration.
* Added support for DVD Drives in Lab VM configuration.
> Add support for mounting ISO files into Virtual DVD Drives in Lab VMs - Fixes #171

- LabBuilder/LabBuilder.psd1
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/192)
> Correct module tags

- LabBuilder/LabBuilder.psd1
- LabBuilder/LabBuilder.psm1
- LabBuilder/docs/changelist.md
- LabBuilder/docs/labbuilderconfig-schema.md
- LabBuilder/dsclibrary/MEMBER_ADRMS.DSC.ps1
- LabBuilder/dsclibrary/MEMBER_FAILOVERCLUSTER_FS.DSC.ps1
- LabBuilder/dsclibrary/MEMBER_JENKINS.DSC.ps1
- LabBuilder/dsclibrary/MEMBER_NANO.DSC.ps1
- LabBuilder/dsclibrary/MEMBER_SQLSERVER2014.DSC.ps1
- LabBuilder/dsclibrary/STANDALONE_JENKINS.DSC.ps1
- LabBuilder/lib/dsc.ps1
- LabBuilder/lib/utils.ps1
- LabBuilder/lib/vm.ps1
- LabBuilder/samples/Sample_WS2012R2_DCandDHCPandEdge.xml
- LabBuilder/samples/Sample_WS2016TP4_DCandDHCPOnly.xml
- LabBuilder/schema/labbuilderconfig-schema.xsd
- LabBuilder/tests/pestertestconfig/PesterTestConfig.OK.xml
- LabBuilder/tests/pestertestconfig/expectedcontent/ExpectedVMs.json
- LabBuilder/tests/unit/LabBuilder.tests.ps1
- LabBuilder/tests/unit/lib/vhd.tests.ps1
- LabBuilder/tests/unit/lib/vm.tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/205)
> Releasing 0.7.5

- .vscode/tasks.json
- LabBuilder/docs/changelist.md
- LabBuilder/support/Convert-LabBuilderConfigSchemaToMD.ps1
In VSCode press CTRL+SHIFT+B to execute the VSCode tasks which will convert the Schema to MD.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/208)
> Feature/add vs code tasks - Fixes #207

- LabBuilder/docs/changelist.md
- LabBuilder/en-us/LabBuilder_LocalizedData.psd1
- LabBuilder/lib/private/utils.ps1
- LabBuilder/lib/public/lab.ps1
- LabBuilder/tests/unit/lib/private/utils.tests.ps1
- README.md
```
* Install-Lab: Force flag added to suppress confirmation messages.
Will attempt to install WS-Man if not installed. Failure will cause install to fail.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/226)
> * Install-Lab: Force flag added to suppress confirmation messages - Fixes #221

- LabBuilder/LabBuilder.psd1
- LabBuilder/docs/changelist.md
- LabBuilder/en-us/LabBuilder_LocalizedData.psd1
- LabBuilder/lib/private/utils.ps1
- LabBuilder/lib/public/lab.ps1
- LabBuilder/lib/public/vm.ps1
- LabBuilder/samples/Sample_WS2016TP5_DCandDHCPOnly.xml
- LabBuilder/tests/pestertestconfig/expectedcontent/ExpectedVMs.json
- LabBuilder/tests/unit/lib/private/utils.tests.ps1
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/227)
> Releasing 0.7.8.0

- LabBuilder/docs/changelist.md
- LabBuilder/en-us/LabBuilder_LocalizedData.psd1
- LabBuilder/lib/private/switch.ps1
- LabBuilder/lib/private/utils.ps1
- LabBuilder/lib/public/lab.ps1
- LabBuilder/tests/unit/lib/private/utils.tests.ps1
- Fixes #230 
- Fixes #223 
* Improved ShouldProcess messages to be easier to read.
* Utils\InstallPackageProviders: Added function for ensuring Package Providers are installed.
* Utils\RegisterPackageSources: Added function for ensuring Package surces are registered. 
* Install-Lab: Added checks to ensure required PackageProviders and PackageSources are available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/231)
> Added checks to ensure required PackageProviders and PackageSources are available

- LabBuilder/docs/changelist.md
- LabBuilder/dsclibrary/DC_FORESTPRIMARY.DSC.ps1
- LabBuilder/dsclibrary/MEMBER_JENKINS.DSC.ps1
- LabBuilder/dsclibrary/MEMBER_SUBCA.DSC.ps1
- LabBuilder/dsclibrary/STANDALONE_JENKINS.DSC.ps1
- LabBuilder/dsclibrary/STANDALONE_ROOTCA.DSC.ps1
- LabBuilder/lib/private/dsc.ps1
- LabBuilder/lib/private/utils.ps1
- LabBuilder/lib/private/vhd.ps1
- LabBuilder/lib/private/vm.ps1
- LabBuilder/lib/public/lab.ps1
- LabBuilder/lib/public/resource.ps1
- LabBuilder/lib/public/switch.ps1
- LabBuilder/lib/public/templatevhd.ps1
- LabBuilder/lib/public/vm.ps1
- LabBuilder/lib/public/vmtemplate.ps1
* Converted all Write-Verbose calls to WriteMessage function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/243)
> Converted all Write-Verbose calls to WriteMessage function - Fixes #234

- LabBuilder/LabBuilder.psd1
- LabBuilder/docs/changelist.md
- LabBuilder/dsclibrary/DC_FORESTPRIMARY.DSC.ps1
- LabBuilder/dsclibrary/MEMBER_JENKINS.DSC.ps1
- LabBuilder/dsclibrary/MEMBER_SUBCA.DSC.ps1
- LabBuilder/dsclibrary/STANDALONE_JENKINS.DSC.ps1
- LabBuilder/dsclibrary/STANDALONE_ROOTCA.DSC.ps1
- LabBuilder/lib/private/dsc.ps1
- LabBuilder/lib/private/switch.ps1
- LabBuilder/lib/private/utils.ps1
- LabBuilder/lib/private/vhd.ps1
- LabBuilder/lib/private/vm.ps1
- LabBuilder/lib/public/lab.ps1
- LabBuilder/lib/public/resource.ps1
- LabBuilder/lib/public/switch.ps1
- LabBuilder/lib/public/templatevhd.ps1
- LabBuilder/lib/public/vm.ps1
- LabBuilder/lib/public/vmtemplate.ps1
* Converted all Write-Verbose calls to WriteMessage function.
* Fix bug when creating a new Management adapter for a new Lab.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/245)
> Releasing 0.8.1.0

- LabBuilder/LabBuilder.psd1
- LabBuilder/docs/changelist.md
- LabBuilder/dsclibrary/MEMBER_DEFAULT.DSC.ps1
- LabBuilder/dsclibrary/MEMBER_IPAM.DSC.ps1
- LabBuilder/lib/private/switch.ps1
- LabBuilder/tests/unit/lib/private/switch.tests.ps1
* Fix bug when creating a new Management adapter for a new Lab and settting a static MAC address on it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/246)
> Releasing 0.8.2.0

- LabBuilder/docs/changelist.md
- LabBuilder/docs/labbuilderconfig-schema.md
- LabBuilder/lib/public/lab.ps1
- LabBuilder/lib/public/resource.ps1
- LabBuilder/schema/labbuilderconfig-schema.xsd
- LabBuilder/tests/pestertestconfig/PesterTestConfig.OK.xml
- LabBuilder/tests/unit/lib/public/lab.tests.ps1
- LabBuilder/tests/unit/lib/public/resource.tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/249)
> Added support for ModulePath attribute on Settings node - Fixes #247

- LabBuilder/docs/changelist.md
- LabBuilder/dsclibrary/MEMBER_ROOTCA.DSC.ps1
- LabBuilder/dsclibrary/MEMBER_SUBCA.DSC.ps1
- LabBuilder/dsclibrary/STANDALONE_ROOTCA.DSC.ps1
- LabBuilder/dsclibrary/STANDALONE_ROOTCA_NOSUBCA.DSC.ps1
* DSCLibrary\*_ROOTCA.DSC.ps1: Fix to support 2.0.0.0 of xADCSDeployment resource.
* DSCLibrary\*_SUBCA.DSC.ps1: Fix to support 2.0.0.0 of xADCSDeployment resource.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/254)
> Fix xADCSWebEnrollment Properties in CA DSC Libraries - Fixes #253

- LabBuilder/en-us/LabBuilder_LocalizedData.psd1
- LabBuilder/lib/private/utils.ps1
- LabBuilder/lib/private/vhd.ps1
- LabBuilder/lib/public/vm.ps1
- LabBuilder/tests/pestertestconfig/expectedcontent/ExpectedTemplates.FromVM.json
- LabBuilder/tests/pestertestconfig/expectedcontent/ExpectedTemplates.json
- LabBuilder/tests/pestertestconfig/expectedcontent/ExpectedVMs.json
- LabBuilder/tests/unit/lib/private/utils.tests.ps1
- LabBuilder/tests/unit/lib/private/vhd.tests.ps1
- LabBuilder/tests/unit/lib/public/resource.tests.ps1
- LabBuilder/tests/unit/lib/public/vm.tests.ps1
Fix the unit tests from the previous PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/258)
> Fix Unit tests

- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/271)
> Release to Master

- LabBuilder/docs/changelist.md
- LabBuilder/lib/private/dsc.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/279)
> Fix error occuring when starting DSC on node with no adapters - Fixes #276

- CHANGELOG.md
- LabBuilder/dsclibrary/MEMBER_SQLSERVER2014.DSC.ps1
- LabBuilder/dsclibrary/MEMBER_SQLSERVER2016.DSC.ps1
- LabBuilder/lib/private/dsc.ps1
- LabBuilder/samples/Sample_WS2012R2_DomainSQL2014.xml
- LabBuilder/samples/Sample_WS2016_DomainSQL2016.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/290)
> Enforce xNetworking v5.0.0.0 is installed and used - Fixes #289

- CHANGELOG.md
- src/lib/private/dsc.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/310)
> Update to NetworkingDsc 7.0.0.0 - Fixes #304

- CHANGELOG.md
- src/lib/private/Get-LabVMManagementIPAddress.ps1
- src/lib/public/Connect-LabVm.ps1
- src/lib/public/Disconnect-LabVm.ps1
- Fixes #314
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/315)
> Fix bug when connecting to a Lab VM when TrustedHosts is empty - Fixes #314

- CHANGELOG.md
- RELEASENOTES.md
- src/LabBuilder.psd1
- src/dsclibrary/MEMBER_NANO.DSC.ps1
- src/lib/public/Start-Lab.ps1
- src/lib/public/Stop-Lab.ps1
- src/samples/Sample_WS2019_DCandDHCPandCA.xml
- Fix infinite loop bug occuring in `Stop-Lab` when Lab VM does not
exist - fixes [Issue #316](https://github.com/PlagueHO/LabBuilder/issues/316).
- Fix infinite loop bug occuring in `Start-Lab` when Lab VM does not
exist.
- DSCLibrary\MEMBER_NANO.DSC.ps1: Rename xOfflineDomainJoin to
OfflineDomainJoin - fixes [Issue #317](https://github.com/PlagueHO/LabBuilder/issues/317).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/318)
> Fix Issues in Start/Stop-Lab when VM Missing - Fixes #316

- CHANGELOG.md
- README.md
- RELEASENOTES.md
- docs/about_LabBuilderSchema.md
- psakefile.ps1
- src/LabBuilder.psd1
- src/dsclibrary/MEMBER_NANO.DSC.ps1
- src/lib/private/Get-LabVMManagementIPAddress.ps1
- src/lib/private/Update-LabDSC.ps1
- src/lib/public/Connect-LabVm.ps1
- src/lib/public/Disconnect-LabVm.ps1
- src/lib/public/New-Lab.ps1
- src/lib/public/Start-Lab.ps1
- src/lib/public/Stop-Lab.ps1
- test/unit/lib/public/vm.tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/319)
> Releasing 1.0.2

- .markdownlint.json
- CHANGELOG.md
- RELEASENOTES.md
- src/LabBuilder.psd1
- src/dsclibrary/DC_FORESTCHILDDOMAIN.DSC.ps1
- src/dsclibrary/DC_FORESTPRIMARY.DSC.ps1
- src/dsclibrary/DC_SECONDARY.DSC.ps1
- src/dsclibrary/MEMBER_DHCP.DSC.ps1
- src/dsclibrary/MEMBER_DHCPDNS.DSC.ps1
- src/dsclibrary/MEMBER_DHCPNPAS.DSC.ps1
- src/dsclibrary/MEMBER_DHCPNPAS2016.DSC.ps1
- src/dsclibrary/MEMBER_DNS.DSC.ps1
- src/dsclibrary/MEMBER_FAILOVERCLUSTER_DHCP.DSC.ps1
- src/dsclibrary/MEMBER_NPS_DFSTEST.DSC.ps1
- src/dsclibrary/MEMBER_ROOTCA.DSC.ps1
- src/dsclibrary/MEMBER_SUBCA.DSC.ps1
- src/dsclibrary/MEMBER_WDS.DSC.ps1
- src/dsclibrary/MEMBER_WEBSERVER.DSC.ps1
- src/dsclibrary/STANDALONE_DHCPDNS.DSC.ps1
- src/dsclibrary/STANDALONE_INTERNET.DSC.ps1
- src/dsclibrary/STANDALONE_ROOTCA.DSC.ps1
- src/dsclibrary/STANDALONE_ROOTCA_NOSUBCA.DSC.ps1
- src/dsclibrary/modules/MyDSCResources/xCertAuthorityServer/xCertAuthorityServer.DSC.Schema.psm1
- src/dsclibrary/modules/MyDSCResources/xDHCPServer/xDHCPServer.DSC.Schema.psm1
- src/lib/private/Copy-LabOdjFile.ps1
- src/lib/private/Set-LabDSC.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/327)
> Releasing 1.0.3

- src/lib/private/Get-LabUnattendFileContent.ps1
- src/lib/public/Connect-LabVm.ps1
- src/lib/public/Install-LabVm.ps1
#295 
#248 
#174 
Small enhancement that allows LabBuilder to create VMs that don't use DSC, used for non-domain joined machines.
@PlagueHO
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/328)
> A few Bug Fixes

- CHANGELOG.md
- README.md
Fixes badges in README.MD to display correct images and links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/358)
> Fix badges

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/370)
> Updating ChangeLog since v1.1.0 +semver:skip

- CHANGELOG.md
- GitVersion.yml
Fix build failures when evaluating next version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/375)
> Fix GitVersion

- CHANGELOG.md
- build.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/376)
> Fix Build Pipeline

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/377)
> Updating ChangeLog since release of v1.2.0

- CHANGELOG.md
- azure-pipelines.yml
Fix CI pipeline deployment stage to ensure detection of Azure DevOps environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/380)
> Fix CI pipeline deployment stage

- CHANGELOG.md
- source/dsclibrary/DC_SECONDARY.DSC.ps1
Thanks for submitting a Pull Request to the LabBuilder project!
Please make sure you have read the [Contributing.md](\.github\CONTRIBUTING.md) document.
Use the pound / hash sign to indicate which GitHub issues this Pull Request fixes, if applicable.
- Fixes #378
For review @PlagueHO - apologies if there is an issue with this pull request - first one I have done.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/labbuilder/379)
> Fix to DC_SECONDARY.DSC.ps1 throws InvalidOperationException #378
